# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_omrf_gibbs <- function(no_states, no_nodes, no_categories, interactions, thresholds, iter) {
    .Call(`_bgms_sample_omrf_gibbs`, no_states, no_nodes, no_categories, interactions, thresholds, iter)
}

em_gamma <- function(interactions, slab_var, theta, xi, no_persons) {
    .Call(`_bgms_em_gamma`, interactions, slab_var, theta, xi, no_persons)
}

em_interaction_var <- function(gamma, slab_var, theta, xi, no_persons) {
    .Call(`_bgms_em_interaction_var`, gamma, slab_var, theta, xi, no_persons)
}

gibbs_sampler <- function(observations, gamma, interactions, thresholds, no_categories, interaction_prior, scale, tau, prop_rel_edges, unit_info, proposal_sd, Index, iter, burnin, n_cat_obs, threshold_alpha, threshold_beta, save = FALSE, caching = TRUE, display_progress = FALSE) {
    .Call(`_bgms_gibbs_sampler`, observations, gamma, interactions, thresholds, no_categories, interaction_prior, scale, tau, prop_rel_edges, unit_info, proposal_sd, Index, iter, burnin, n_cat_obs, threshold_alpha, threshold_beta, save, caching, display_progress)
}

gradient_thresholds_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_gradient_thresholds_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

gradient_thresholds_pseudoposterior <- function(interactions, thresholds, observations, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_gradient_thresholds_pseudoposterior`, interactions, thresholds, observations, no_categories, threshold_alpha, threshold_beta)
}

gradient_interactions_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_gradient_interactions_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

gradient_interactions_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var) {
    .Call(`_bgms_gradient_interactions_pseudoposterior_normal`, interactions, thresholds, observations, no_categories, interaction_var)
}

gradient_interactions_pseudoposterior_cauchy <- function(interactions, thresholds, observations, no_categories, scale) {
    .Call(`_bgms_gradient_interactions_pseudoposterior_cauchy`, interactions, thresholds, observations, no_categories, scale)
}

hessian_thresholds_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_hessian_thresholds_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

hessian_thresholds_pseudoposterior <- function(interactions, thresholds, observations, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_hessian_thresholds_pseudoposterior`, interactions, thresholds, observations, no_categories, threshold_alpha, threshold_beta)
}

hessian_interactions_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_hessian_interactions_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

hessian_interactions_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var) {
    .Call(`_bgms_hessian_interactions_pseudoposterior_normal`, interactions, thresholds, observations, no_categories, interaction_var)
}

hessian_interactions_pseudoposterior_cauchy <- function(interactions, thresholds, observations, no_categories, scale) {
    .Call(`_bgms_hessian_interactions_pseudoposterior_cauchy`, interactions, thresholds, observations, no_categories, scale)
}

hessian_crossparameters <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_hessian_crossparameters`, interactions, thresholds, observations, no_categories)
}

log_pseudolikelihood <- function(interactions, thresholds, observations, no_categories) {
    .Call(`_bgms_log_pseudolikelihood`, interactions, thresholds, observations, no_categories)
}

log_unnormalized_pseudoposterior_normal <- function(interactions, thresholds, observations, no_categories, interaction_var, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_log_unnormalized_pseudoposterior_normal`, interactions, thresholds, observations, no_categories, interaction_var, threshold_alpha, threshold_beta)
}

log_unnormalized_pseudoposterior_cauchy <- function(interactions, thresholds, observations, scale, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_log_unnormalized_pseudoposterior_cauchy`, interactions, thresholds, observations, scale, no_categories, threshold_alpha, threshold_beta)
}

dlap <- function(interaction, mu = 0.0, b = 1.0, log = TRUE) {
    .Call(`_bgms_dlap`, interaction, mu, b, log)
}

log_unnormalized_pseudoposterior_laplace <- function(interactions, thresholds, observations, scale, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_log_unnormalized_pseudoposterior_laplace`, interactions, thresholds, observations, scale, no_categories, threshold_alpha, threshold_beta)
}

dh <- function(interaction, scale = 1, tau = 1, prop_rel_edges = 1, log = FALSE, no_categories = 1L, no_persons = 1, no_interactions = 1) {
    .Call(`_bgms_dh`, interaction, scale, tau, prop_rel_edges, log, no_categories, no_persons, no_interactions)
}

log_unnormalized_pseudoposterior_horseshoe <- function(interactions, thresholds, observations, scale, tau, prop_rel_edges, no_categories, threshold_alpha = 1.0, threshold_beta = 1.0, no_persons = 1, no_interactions = 1) {
    .Call(`_bgms_log_unnormalized_pseudoposterior_horseshoe`, interactions, thresholds, observations, scale, tau, prop_rel_edges, no_categories, threshold_alpha, threshold_beta, no_persons, no_interactions)
}

emvs_log_unnormalized_pseudoposterior <- function(interactions, thresholds, observations, no_categories, xi, slab_var, theta = 0.5, hierarchical = FALSE, indicator_alpha = 1.0, indicator_beta = 1.0, threshold_alpha = 1.0, threshold_beta = 1.0) {
    .Call(`_bgms_emvs_log_unnormalized_pseudoposterior`, interactions, thresholds, observations, no_categories, xi, slab_var, theta, hierarchical, indicator_alpha, indicator_beta, threshold_alpha, threshold_beta)
}

